# 서버 포트 관련
server:
  port: 8084

# mysql, jpa 관련
spring:
  application:
    name: toyProject
  datasource:
    url: jdbc:mysql://localhost:3307/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    com:
      mamully: TRACE


